routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('project', 'ProjectController');
Route::resource('user', 'UserController');
Route::resource('totaltime', 'TotalTimeController');
Route::resource('projecttime', 'ProjectTimeController');
//Les routes d'authentification
Auth::routes();
//Route accueil
Route::get('/', 'HomeController@index')
    ->name('home');
//Route de la page principale admin avec le middleware qui vérifie que le user est bien admin
Route::get('/admin', 'AdminController@admin')    
    ->middleware('is_admin')    
    ->name('admin');
//Route groupé avec préfix admin    
Route::group(['prefix'=>'admin'], function() {
    Route::get('/ajouter-client', 'ClientController@create')->name('client.create');
    Route::get('/clients', 'ClientController@index')->name('client.list');
    Route::get('/client/{id}', 'ClientController@show')->name('client.show');
    Route::post('/clients', 'ClientController@store')->name('client.store');
    Route::get('/ajouter-projet', 'ProjectController@create')->name('project.create');
    Route::get('/projets', 'ProjectController@index')->name('project.list');
    Route::get('/projet/{id}', 'ProjectController@show')->name('project.show');
    Route::get('/utilisateurs', 'UserController@index')->name('user.list');
    Route::get('/ajouter-utilisateur', 'UserController@create')->name('user.create');
    Route::get('/utilisateur/{id}', 'UserController@show')->name('user.show');
    Route::post('/utilisateurs', 'UserController@store')->name('user.store');
    Route::post('/projet', 'CrossController@store')->name('cross.store');
});
//Route de déconnexion 
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model 
{

    protected $table = 'projects';
    public $timestamps = true;
    protected $fillable = ['name', 'clients_id'];


}

app/Http/Controllers/ProjectController.php
<?php 

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Project;
class ProjectController extends Controller 
{

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    //On récupère l'id et le name de la table projects
    $projects = DB::table('projects')->select('id', 'name')->get();
    return view('project.index')->with('projects', $projects);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
    //On récupère 'id' et 'name' de la table 'clients'
    $clients = DB::table('clients')->select('id', 'name')->get();
    return view('project.create')->with('clients', $clients);

  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
    $request->validate([
      'name'=>'required',
      'client_name'=>'required'
  ]);
  //Nouveau Project
  $project = new Project([
      'name'=> $request->get('name'),
      'clients_id'=>$request->get('client_name')
  ]);
  $project->save();
  return redirect('/admin/projets')->with('success', 'projet ajouté !');

  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    //On récupère tout de la table cross
    $usersCross = DB::table('cross')->select('*')->get();
    //On récupère 'id' et 'name' de la table 'user'
    $users = DB::table('users')->select('id', 'name')->get();
    //On récupère 'id' et 'name' de la table 'projects'
    $projects = DB::table('projects')->select('id', 'name')->get();
    //On récupère $projects où l'id est égal à $id
    $project = $projects->where('id', $id);
    return view('project.show', ['project' => Project::findOrFail($id)], compact('project', $project, 'usersCross', $usersCross, 'users', $users));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update($id)
  {
    
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    
  }
  
}

?>

resources/views/project/create.blade.php
@extends('layout')
@section('content')
<form action="{{ route('project.store') }}" method="POST" class="text-center border border-light p-5 my-5">
    @csrf
    <p class="h4 mb-4">Ajouter un projet</p>
    <input type="text" class="form-control mb-4" placeholder="Nom du projet" name="name">
    <select name="client_name">
    @forelse ($clients as $client)
        <option value="{{ $client->id}}">{{ $client->name}}</option>
    @empty 
    Créez un client
    @endforelse
    </select>    
    <button class="btn btn-info btn-block my-4" type="submit">Ajouter</button>
</form>

@endsection

resources/views/project/index.blade.php
@extends('layout')
@section('content')
    
<div class="jumbotron jumbotron-fluid">
    <a href="{{ URL('/admin') }}">
    <i class="fas fa-arrow-left"></i> Admin panel
    </a>
    <div class="container">
        <h1>Liste des projets</h1>
        @forelse ($projects as $project)
        <ul>
            <li><a href="{{ URL('/admin/projet/' .$project->id) }}">{{ $project->name}}</a></li>
        </ul>
        @empty
        Pas de projet.    
        @endforelse
        <a class="btn btn-primary" href="{{URL('/admin/ajouter-projet')}}">Ajouter un projet</a>
    </div>
</div>
@endsection

resources/views/project/show.blade.php
@extends('layout')
@section('content')
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <a href="{{ URL('/admin/projets') }}">
    <i class="fas fa-arrow-left"></i> Liste des projets
    </a> 
    <h1 class="text-align-center">Nom du projet : {{ $project->name }}</h1>
    <h2>Utilisateurs :</h2>
    @forelse ($usersCross as $user)
    <ul>
      <li>{{$user->users_name}}</li>
    </ul>
    @empty
    Personne n'a entamé ce projet.
    @endforelse
    <!--Modal d'ajout d'utilisateur sur un projet -->
    <div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold">Assigner ce projet à des utilisateurs</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body mx-3">
            <form action="{{ route('cross.store') }}" method="POST" class="text-center border border-light p-5 my-5">
              @csrf 
              <input type="hidden"  name="projects_id" value="{{$project->id}}">
              {{--Variable inputId afin d'incrémenter l'id de la modal = defaultUnchecked et for = defaultUnchecked --}}
              <?php 
              $inputId= 1;
              $labelId= 1;
              ?>
              @forelse ($users as $user)
              <div class="md-form mb-5">
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" id="defaultUnchecked<?php echo ++$inputId; ?>" name="users_id" value="{{$user->id}}">
                  <label class="custom-control-label" for="defaultUnchecked<?php echo ++$labelId; ?>">{{ $user->name }}</label>
                </div>
              </div>
              @empty
                Il n'y a pas d'utilisateur.
              @endforelse
              <input type="hidden" value="{{$project->name}}" name="projects_name">
                <div class="modal-footer d-flex justify-content-center">
                    <button class="btn btn-default" type="submit">Assigner</button>
                </div>
            </form>    
          </div>
        </div>
      </div>
    </div>    
    <div class="text-center">
      <a href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#modalLoginForm">Assigner ce projet à des utilisateurs</a>
    </div>
  </div>
</div>
@endsection